swagger: '2.0'
info:
  title: "Спортик и точка"
  description: "Описание API"
  version: "1.0"
components:
  schemas:
    NotFoundException:
      type: object
      properties:
        success:
          type: boolean
          description: "Результат операции"
        error:
          type: string
          description: "Сообщение о том, кто или что не найдено"
    Unauthorized:
      type: object
      properties:
        success:
          type: boolean
          description: "Результат операции"
        error:
          type: string
          description: "Сообщение об ошибке"
    BadRequest:
      type: object
      properties:
        success:
          type: boolean
          description: "Результат операции"
        error:
          type: string
          description: "Сообщение об ошибке"
        details:
          type: string
          description: "Конкретное описание ошибок"
    Conflict:
      type: object
      properties:
        free:
          type: boolean
          description: "Проверка доступности email"
    InvalidRoleException:
      type: object
      properties:
        success:
          type: boolean
          description: "Результат операции"
        error:
          type: string
          description: "Описание ошибки"
    graph_data:
      type: object
      required:
        - date
        - users_with_premium
        - users_without_premium
      properties:
        date:
          type: string
          description: Дата активности в формате "гггг-мм-дд"
        users_with_premium:
          type: integer
          description: Количество премиум-пользователей
        users_without_premium:
          type: integer
          description: Количество обычных пользователей
    ActivityType:
      type: string
      enum:
        - running
        - swimming
        - cycling
    ActivityResponse:
      type: object
      required:
        - id
        - activity_type
        - image
        - date
        - avg_speed
        - distance_in_meters
        - duration
        - calories_burned
      properties:
        id:
          type: integer
          description: ID активности
        activity_type:
          type: string
          description: Тип активности (running, cycling, swimming)
        image:
          type: string
          description: Отображение пути на карте
        date:
          type: string
          format: date
          description: Дата активности в формате "гггг-мм-дд"
        avg_speed:
          type: number
          description: Средняя скорость
        distance_in_meters:
          type: integer
          description: Расстояние в метрах
        duration:
          type: integer
          description: Продолжительность в секундах
        calories_burned:
          type: integer
          description: Сожженные калории
    PremiumActivityResponse:
      type: object
      required:
        - id
        - activity_type
        - image
        - date
        - avg_speed
        - distance_in_meters
        - duration
        - calories_burned
      properties:
        id:
          type: integer
          description: "ID активности"
        activity_type:
          type: string
          description: "Тип активности (running, cycling, swimming)"
        image:
          type: string
          description: "Отображение пути на карте"
        date:
          type: string
          format: date
          description: "Дата активности в формате 'гггг-мм-дд'"
        avg_speed:
          type: number
          description: "Средняя скорость"
        distance_in_meters:
          type: integer
          description: "Расстояние в метрах"
        duration:
          type: integer
          description: "Продолжительность в секундах"
        calories_burned:
          type: integer
          description: "Сожженные калории"
    AchievementResponse:
      type: object
      required:
        - id
        - name
        - image
        - distance
      properties:
        id:
          type: integer
          description: ID достижения
        name:
          type: string
          description: Название достижения
        image:
          type: string
          description: Картинка достижения
        distance:
          type: integer
          description: Расстояние для получения ачивки
    UserRating:
      type: object
      required:
        - id
        - name
        - image
        - role
        - rating
        - total_activities_count
        - total_distance_in_meters
        - total_time
        - total_calories
        - avg_speed
        - average_distance_in_meters
        - average_time
        - average_calories
        - achievements
      properties:
        id:
          type: integer
          description: "ID пользователя"
        name:
          type: string
          description: "Имя пользователя"
        image:
          type: string
          description: "Фото пользователя"
        role:
          type: string
          description: "Роль пользователя"
        rating:
          type: integer
          description: "Место в рейтинге"
        total_activities_count:
          type: integer
          description: "Количество активностей"
        total_distance_in_meters:
          type: integer
          description: "Общее расстояние"
        total_time:
          type: integer
          description: "Общее время"
        total_calories:
          type: integer
          description: "Общее кол-во калорий"
        avg_speed:
          type: number
          format: float
          description: "Средняя скорость"
        average_distance_in_meters:
          type: integer
          description: "Среднее расстояние"
        average_time:
          type: integer
          description: "Среднее время"
        average_calories:
          type: integer
          description: "Среднее количество калорий"
        achievements:
          type: array
          items:
            $ref: '#/components/schemas/AchievementResponse'
paths:
  /user/register:
    post:
      tags:
        - "Регистрация"
      summary: "Создать новый аккаунт пользователя"
      parameters:
        - name: "email"
          in: "header"
          required: true
          type: "string"
          description: "Email пользователя"
        - name: "register_data"
          in: "body"
          required: true
          schema:
            id: "RegisterRequest"
            required:
              - "name"
              - "weight"
              - "avatar"
              - "phone"
              - "birthday"
              - "password_hash"
            properties:
              name:
                type: "string"
                description: "Имя пользователя"
              weight:
                type: "integer"
                description: "Вес пользователя"
              avatar:
                type: "string"
                description: "Аватар пользователя"
              phone:
                type: "string"
                description: "Телефон пользователя"
              birthday:
                type: "string"
                description: "Дата рождения пользователя в формате 'гггг-мм-дд'"
              password_hash:
                type: "string"
                description: "Пароль пользователя"
      responses:
        '201':
          description: "Успешная регистрация"
          schema:
            id: "RegisterResponse"
            properties:
              success:
                type: "boolean"
                description: "Результат регистрации"
              access_token:
                type: "string"
                description: "Токен доступа пользователя"
              user_id:
                type: "integer"
                description: "ID пользователя"
        '400':
          description: "Ошибка введенных данных"
          schema:
            type: object
            $ref: '#/components/schemas/BadRequest'
        '409':
          description: "Ошибка, если email уже используется"
          schema:
            type: object
            $ref: '#/components/schemas/Conflict'
  /admin/register:
    post:
      tags:
        - "Регистрация"
      summary: "Создать новый аккаунт администратора"
      parameters:
        - name: "email"
          in: "header"
          required: true
          type: "string"
          description: "Email администратора"
        - name: "register_data"
          in: "body"
          required: true
          schema:
            id: "RegisterAdminRequest"
            required:
              - "name"
              - "avatar"
              - "phone"
              - "birthday"
              - "password_hash"
            properties:
              name:
                type: "string"
                description: "Имя администратора"
              avatar:
                type: "string"
                description: "Аватар администратора"
              phone:
                type: "string"
                description: "Телефон администратора"
              birthday:
                type: "string"
                description: "Дата рождения администратора в формате 'гггг-мм-дд'"
              password_hash:
                type: "string"
                description: "Пароль администратора"
      responses:
        '201':
          description: "Успешная регистрация"
          schema:
            id: "RegisterAdminResponse"
            properties:
              success:
                type: "boolean"
                description: "Результат регистрации"
              access_token:
                type: "string"
                description: "Токен доступа администратора"
              admin_id:
                type: "integer"
                description: "ID администратора"
        '400':
          description: "Ошибка введенных данных"
          schema:
            type: object
            $ref: '#/components/schemas/BadRequest'
        '409':
          description: "Ошибка, если email уже используется"
          schema:
            type: object
            $ref: '#/components/schemas/Conflict'
  /login:
    post:
      tags:
        - "Вход в аккаунт"
      summary: "Войти в аккаунт"
      parameters:
        - name: "login_data"
          in: "body"
          required: true
          schema:
            id: "LoginRequest"
            properties:
              email:
                type: "string"
                description: "Email пользователя"
              password:
                type: "string"
                description: "Пароль пользователя"
      responses:
        '200':
          description: "Успешный вход"
          schema:
            id: "LoginResponse"
            properties:
              success:
                type: "boolean"
                description: "Результат входа"
              access_token:
                type: "string"
                description: "Токен доступа пользователя"
              user_id:
                type: "integer"
                description: "ID пользователя"
              role:
                type: "string"
                description: "Роль пользователя"
        '400':
          description: "Ошибка введенных данных"
          schema:
            type: object
            $ref: '#/components/schemas/BadRequest'
        '401':
          description: "Неправильный пароль"
          schema:
            type: object
            $ref: '#/components/schemas/Unauthorized'
        '403':
          description: "Пользователь заблокирован"
          schema:
            type: object
            $ref: '#/components/schemas/InvalidRoleException'
        '404':
          description: "Пользователь не найден"
          schema:
            type: object
            $ref: '#/components/schemas/NotFoundException'
  /activities:
    post:
      tags:
        - "Взаимодействие с активностями"
      summary: "Добавить активность"
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
          description: Токен доступа пользователя
        - name: activity_data
          in: body
          required: true
          schema:
            id: AddActivityRequest
            required:
              - activity_type
              - date
              - image
              - avg_speed
              - distance_in_meters
              - duration
              - calories_burned
            properties:
              activity_type:
                type: string
                enum: [ 'RUNNING', 'SWIMMING', 'CYCLING' ]
                description: "Тип активности"
              date:
                type: string
                description: Дата активности
              image:
                type: string
                description: Отображение пути на карте
              avg_speed:
                type: number
                format: float
                description: Средняя скорость
              distance_in_meters:
                type: integer
                description: Расстояние в метрах
              duration:
                type: integer
                description: Длительность активности в секундах
              calories_burned:
                type: integer
                description: Сожженные калории
      responses:
        201:
          description: Успешное добавление активности
          schema:
            id: AddActivityResponse
            properties:
              success:
                type: boolean
                description: Результат добавления активности
              activity_id:
                type: integer
                description: ID активности
        400:
          description: "Ошибка введенных данных"
          schema:
            type: object
            $ref: '#/components/schemas/BadRequest'
        401:
          description: Токен некорректный
          schema:
            type: object
            $ref: '#/components/schemas/Unauthorized'
        403:
          description: Доступ запрещен (Forbidden)
          schema:
            type: object
            $ref: '#/components/schemas/InvalidRoleException'
        404:
          description: Ошибка, если пользователь не найден
          schema:
            type: object
            $ref: '#/components/schemas/NotFoundException'
    get:
      tags:
        - "Взаимодействие с активностями"
      summary: Получить список активностей
      description: Возвращает список всех активностей пользователя.
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
          description: Токен доступа пользователя
      responses:
        200:
          description: Успешный запрос
          schema:
            id: ActivityResponse
            properties:
              success:
                type: boolean
                description: Результат добавления активности
              activities:
                type: array
                items:
                  $ref: '#/components/schemas/ActivityResponse'
          examples:
            NoActivities:
              description: Нет активностей
              value:
                success: true
                message: No activities yet
            SingleActivity:
              summary: Пример одной активности
              value:
                id: 1
                activity_type: "running"
                image: "/images/running_map.png"
                date: "2024-05-01"
                avg_speed: 5.5
                distance_in_meters: 10000
                duration: 3600
                calories_burned: 500
              MultipleActivities:
                summary: Пример нескольких активностей
                value:
                  - id: 1
                    activity_type: "cycling"
                    image: "/images/cycling_map.png"
                    date: "2024-05-02"
                    avg_speed: 15.0
                    distance_in_meters: 20000
                    duration: 7200
                    calories_burned: 1000
                  - id: 2
                    activity_type: "swimming"
                    image: "/images/swimming_map.png"
                    date: "2024-05-03"
                    avg_speed: 2.0
                    distance_in_meters: 1000
                    duration: 1200
                    calories_burned: 300
        401:
          description: Токен некорректный
          schema:
            type: object
            $ref: '#/components/schemas/Unauthorized'
        403:
          description: Доступ запрещен (Forbidden)
          schema:
            type: object
            $ref: '#/components/schemas/InvalidRoleException'
          examples:
            invalid_role:
              summary: Пример ошибки доступа
              value:
                success: false
                error: "Недостаточно прав для доступа"
        404:
          description: Ошибка, если пользователь не найден
          schema:
            type: object
            $ref: '#/components/schemas/NotFoundException'
  /admin/action:
    put:
      tags:
        - "Взаимодействие администраторов с пользователями"
      summary: "Заблокировать, разблокировать, забрать премиум"
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
          description: Токен доступа администратора
        - name: request_data
          in: body
          required: true
          schema:
            id: AdminModifyActionRequest
            properties:
              user_id:
                type: integer
                description: ID пользователя
              action:
                type: string
                enum: [ block, unblock, revoke_premium ]
                description: Выбранное действие
      responses:
        200:
          description: Успешная модификация статуса пользователя
          schema:
            id: AdminModifyActionResponse
            properties:
              success:
                type: boolean
                description: Результат действия
              action:
                type: string
                description: Выполненное действие
        400:
          description: "Ошибка введенных данных"
          schema:
            type: object
            $ref: '#/components/schemas/BadRequest'
        401:
          description: Токен некорректный
          schema:
            type: object
            $ref: '#/components/schemas/Unauthorized'
        403:
          description: Доступ запрещен (Forbidden)
          schema:
            type: object
            $ref: '#/components/schemas/InvalidRoleException'
        404:
          description: Пользователь или администратор не найдены
          schema:
            type: object
            $ref: '#/components/schemas/NotFoundException'
        409:
          description: Действие недоступно
          schema:
            type: object
            $ref: '#/components/schemas/Conflict'
    post:
      tags:
        - "Взаимодействие администраторов с пользователями"
      summary: "Выдать премиум-подписку"
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
          description: Токен доступа администратора
        - name: request_data
          in: body
          required: true
          schema:
            id: AdminGrantPremiumRequest
            properties:
              user_id:
                type: integer
                description: ID пользователя
      responses:
        200:
          description: Успешная выдача премиума пользователю
          schema:
            id: AdminGrantPremiumResponse
            properties:
              success:
                type: boolean
                description: Результат действия
              action:
                type: string
                description: Выполненное действие
        401:
          description: Токен некорректный
          schema:
            type: object
            $ref: '#/components/schemas/Unauthorized'
        403:
          description: Доступ запрещен (Forbidden)
          schema:
            type: object
            $ref: '#/components/schemas/InvalidRoleException'
        404:
          description: Пользователь или администратор не найдены
          schema:
            type: object
            $ref: '#/components/schemas/NotFoundException'
        409:
          description: Действие недоступно
          schema:
            type: object
            $ref: '#/components/schemas/Conflict'
  /premium:
    post:
      tags:
        - "Взаимодействие с премиум-подпиской"
      summary: "Покупка премиума пользователем"
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
          description: Токен доступа пользователя
        - name: card_data
          in: body
          required: true
          schema:
            id: BuyPremiumRequest
            properties:
              card_name:
                type: string
                description: Имя карты
              card_number:
                type: string
                description: Номер карты
              month:
                type: integer
                description: Месяц срока действия
              year:
                type: integer
                description: Год срока действия
              cvv:
                type: integer
                description: CVV карты
      responses:
        201:
          description: Успешная покупка премиума
          schema:
            id: GetPremiumResponse
            properties:
              success:
                type: boolean
                description: Результат покупки
              timestamp:
                type: string
                description: Дата начала премиум подписки
        400:
          description: "Ошибка введенных данных"
          schema:
            type: object
            $ref: '#/components/schemas/BadRequest'
        401:
          description: Токен некорректный
          schema:
            type: object
            $ref: '#/components/schemas/Unauthorized'
        403:
          description: Доступ запрещен (Forbidden)
          schema:
            type: object
            $ref: '#/components/schemas/InvalidRoleException'
        404:
          description: Пользователь не найден
          schema:
            type: object
            $ref: '#/components/schemas/NotFoundException'
  /data:
    get:
      tags:
        - "Личные данные"
      summary: "Получить личные данные"
      description: "Возвращает личные данные"
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
          description: Токен доступа пользователя
      responses:
        200:
          description: Успешный запрос
          schema:
            id: GetCurrentDataResponse
            type: object
            properties:
              id:
                type: integer
                description: ID пользователя
              name:
                type: string
                description: Имя пользователя
              image:
                type: string
                description: Аватар пользователя
              phone:
                type: string
                description: Телефон пользователя
              birthday:
                type: string
                description: Дата рождения пользователя в формате "гггг-мм-дд"
              weight:
                type: integer
                description: Вес пользователя (для админа нет веса)
        401:
          description: Токен некорректный
          schema:
            type: object
            $ref: '#/components/schemas/Unauthorized'
        404:
          description: Ошибка, если пользователь не найден
          schema:
            type: object
            $ref: '#/components/schemas/NotFoundException'
        403:
          description: Доступ запрещен (Forbidden)
          schema:
            type: object
            $ref: '#/components/schemas/InvalidRoleException'
    put:
      tags:
        - "Личные данные"
      summary: "Изменить личные данные"
      description: "Изменяет личные данные"
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
          description: Токен доступа пользователя
        - name: new_data
          in: body
          required: true
          schema:
            id: ChangeDataUserRequest
            properties:
              name:
                type: string
                description: Новое имя пользователя
              image:
                type: string
                description: Новое фото пользователя
              phone:
                type: string
                description: Новый телефон пользователя
              birthday:
                type: string
                description: Новая дата рождения пользователя в формате "гггг-мм-дд"
              weight:
                type: integer
                description: Новый вес пользователя (для админов нет)
      responses:
        200:
          description: Успешный запрос
          schema:
            id: ChangeDataUserResponse
            type: object
            properties:
              success:
                type: boolean
                description: Результат запроса
        400:
          description: "Ошибка введенных данных"
          schema:
            type: object
            $ref: '#/components/schemas/BadRequest'
        401:
          description: Токен некорректный
          schema:
            type: object
            $ref: '#/components/schemas/Unauthorized'
        404:
          description: Ошибка, если пользователь не найден
          schema:
            type: object
            $ref: '#/components/schemas/NotFoundException'
        403:
          description: Доступ запрещен (Forbidden)
          schema:
            type: object
            $ref: '#/components/schemas/InvalidRoleException'
  /premium/cancel:
    put:
      tags:
        - "Взаимодействие с премиум-подпиской"
      summary: "Отменить премиум-подписку"
      description: "Отменяет премиум-подписку"
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
          description: Токен доступа пользователя
      responses:
        200:
          description: Успешный запрос
          schema:
            id: CancelPremiumResponse
            type: object
            properties:
              success:
                type: boolean
                description: Результат запроса
        401:
          description: Токен некорректный
          schema:
            type: object
            $ref: '#/components/schemas/Unauthorized'
        404:
          description: Ошибка, если пользователь не найден
          schema:
            type: object
            $ref: '#/components/schemas/NotFoundException'
  /user/profile:
    get:
      tags:
        - "Личный профиль"
      summary: "Получить профиль пользователя"
      description: "Возвращает данные для профиля пользователя"
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
          description: Токен доступа пользователя
        - name: period
          in: query
          required: true
          type: string
          enum: [ week, month, year, all_time ]
          description: Период времени для статистики
      responses:
        200:
          description: Успешный запрос
          schema:
            id: UserProfileResponse
            properties:
              name:
                type: string
                description: Имя пользователя
              image:
                type: string
                description: Фото пользователя
              statistics:
                type: object
                description: Статистика пользователя
                properties:
                  total_distance_in_meters:
                    type: integer
                    description: Общее расстояние в метрах
                  total_time:
                    type: integer
                    description: Общее время
                  total_calories:
                    type: integer
                    description: Общее количество калорий
              achievements:
                type: array
                items:
                  $ref: '#/components/schemas/AchievementResponse'
        401:
          description: Токен некорректный
          schema:
            type: object
            $ref: '#/components/schemas/Unauthorized'
        403:
          description: Доступ запрещен (Forbidden)
          schema:
            type: object
            $ref: '#/components/schemas/InvalidRoleException'
        404:
          description: Ошибка, если пользователь или статистика не найдены
          schema:
            type: object
            $ref: '#/components/schemas/NotFoundException'
  /admin/profile:
    get:
      tags:
        - "Личный профиль"
      summary: "Получить профиль администратора"
      description: "Возвращает данные для профиля администратора"
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
          description: Токен доступа пользователя
      responses:
        200:
          description: Успешный запрос
          schema:
            id: AdminProfileResponse
            properties:
              name:
                type: string
                description: Имя админа
              image:
                type: string
                description: Фото админа
        401:
          description: Токен некорректный
          schema:
            type: object
            $ref: '#/components/schemas/Unauthorized'
        403:
          description: Доступ запрещен (Forbidden)
          schema:
            type: object
            $ref: '#/components/schemas/InvalidRoleException'
        404:
          description: Ошибка, если администратор не найден
          schema:
            type: object
            $ref: '#/components/schemas/NotFoundException'
  /rating:
    get:
      tags:
        - "Рейтинг"
      summary: "Получить рейтинг пользователей"
      description: "Возвращает данные для рейтинга пользователей"
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
          description: "Токен доступа пользователя"
      responses:
        200:
          description: "Успешный запрос"
          schema:
            id: UserRatingResponse
            properties:
              users:
                type: array
                items:
                  $ref: '#/components/schemas/UserRating'
        401:
          description: "Токен некорректный"
          schema:
            type: object
            $ref: '#/components/schemas/Unauthorized'
        404:
          description: "Ошибка, если пользователь или статистика не найдены"
          schema:
            type: object
            $ref: '#/components/schemas/NotFoundException'
  /user/premium/statistics:
    get:
      tags:
        - "Статистика"
      summary: "Получить статистику для премиум-пользователя"
      description: "Возвращает данные для премиум-статистики"
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
          description: "Токен доступа пользователя"
        - name: period
          in: query
          required: true
          type: string
          enum: [ week, month, year, all_time ]
          description: "Период времени для статистики"
      responses:
        200:
          description: "Успешный запрос"
          schema:
            id: PremiumStatisticsResponse
            properties:
              total_distance_in_meters:
                type: integer
                description: "Общее расстояние в метрах"
              total_time:
                type: integer
                description: "Общее время"
              total_calories:
                type: integer
                description: "Общее количество калорий"
              avg_speed:
                type: number
                format: float
                description: "Средняя скорость"
              activities:
                type: array
                items:
                  $ref: '#/components/schemas/PremiumActivityResponse'
        401:
          description: "Токен некорректный"
          schema:
            type: object
            $ref: '#/components/schemas/Unauthorized'
        403:
          description: Доступ запрещен (Forbidden)
          schema:
            type: object
            $ref: '#/components/schemas/InvalidRoleException'
        404:
          description: "Ошибка, если пользователь или статистика не найдены"
          schema:
            type: object
            $ref: '#/components/schemas/NotFoundException'
  /admin/statistics:
    get:
      tags:
        - "Статистика"
      summary: "Получить статистику для администраторов"
      description: "Возвращает данные для статистики администратора"
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
          description: Токен доступа администратора
        - name: period
          in: query
          required: true
          type: string
          enum: [ week, month, year, all_time ]
          description: Период времени для статистики
      responses:
        200:
          description: Успешный запрос
          schema:
            id: AdminStatisticsRequest
            properties:
              total_users:
                type: integer
                description: Общее количество пользователей приложения
              premium_users:
                type: integer
                description: Общее количество премиум-пользователей приложения
              graph_data:
                type: array
                items:
                  $ref: '#/components/schemas/graph_data'
        401:
          description: Токен некорректный
          schema:
            type: object
            $ref: '#/components/schemas/Unauthorized'
        403:
          description: Доступ запрещен (Forbidden)
          schema:
            type: object
            $ref: '#/components/schemas/InvalidRoleException'
        404:
          description: Ошибка, если пользователь или статистика не найдены
          schema:
            type: object
            $ref: '#/components/schemas/NotFoundException'